- Source/igtlClientSocket.cxx
- Source/igtlClientSocket.h
When auto-connect is chosen from Slicer, there is continuous spam from the constant reconnect attempts. This change enables the possibility of controlling the output behavior.
Further commits in the Slicer code will disable the log spam.
> ENH: Reducing Slicer log spam by only outputting a connection failed message if requested

- Source/igtlCapabilityMessage.h
Using angle brackets for the include fails in our environment. All other messages use local, i.e. quotation marks, for including and can be
compiled.
> replaced angle brackets by quotation marks (this is the way including is done for all other messages)

- Examples/Imager/ImagerClient3.cxx
- Examples/Imager/ImagerServer3.cxx
- Examples/Point/PointClient3.cxx
- Examples/Point/PointServer3.cxx
- Source/igtlMessageBase.cxx
- Source/igtlMessageBase.h
1. The message id could be set now, previous it was set to 0 and cannot be modified
2. The coding scheme is set to default value "3", which corresponding to US-ASCII2 
3. Example server and client updated accordingly
> Message id and coding scheme improved

- Source/igtlMessageBase.cxx
Solution is to set copied header version before calling allocate/copy functions.
> BUG: Message copy fails due to mismatch version

- Source/igtlMessageBase.cxx
- Source/igtlMessageBase.h
- Testing/igtlCommandMessageTest.cxx
- Testing/igtlMessageFormat2TestMacro.h
- Testing/igtlPositionMessageTest.cxx
- Testing/igtlTrackingDataMessageTest.cxx
- Testing/igtlTrajectoryMessageTest.cxx
- Testing/igtlTransformMessageTest.cxx
This prevents repacking an existing message if contents have changed.
> BUG: m_IsBodyPacked flag is not properly managed

- OpenIGTLinkConfigPlatform.cmake
- Source/igtlutil/CMakeLists.txt
- igtl_typeconfig.h.in
Some very minor changes to enable the building of OpenIGTLink as a UWP DLL
CMake:
CMAKE_SYSTEM_NAME = "WindowsStore"
CMAKE_SYSTEM_VERSION = "10.0"
> ENH: Enabling support for UWP build

- Source/VideoStreaming/VideoStreaming.cmake
Thank you for updating OpenIGTLink to support video streaming! This is really exciting. I run into some minor issues when compiling on Windows for x64 and VP9 enabled. This was caused by the assumption that source and build folder for libvpx are the same (by default there are not however). The other issue was that Win32 in some path rather than $(Platform).
> Fixes for building with VP9 and x64

- Source/igtlPolyDataMessage.cxx
- Source/igtlPolyDataMessage.h
Added a couple of accessors for polydata message
New enum values are added such that they maintain backwards compatibility
> ENH: Enable support for texture coords being accessible by type

- Source/igtlGeneralSocket.cxx
- Source/igtlUDPServerSocket.cxx
inet_pton() is not supported on Windows XP
Replaced calls to inet_pton() with inet_addr().
Related to: https://github.com/PlusToolkit/PlusLib/issues/200
> Fix support for Windows XP applications

- Source/igtlMessageFactory.cxx
Add the IMGMETA, GET_IMGMETA, LBMETA, and GET_LBMETA messages to igtlMessageFactory.
Part of a fix for: https://github.com/PlusToolkit/PlusLib/issues/249
> ENH: Add IMGMETA, GET_IMGMETA, LBMETA, and GET_LBMETA to message factory

- Source/VideoStreaming/igtlH264Encoder.cxx
I couldn't compile the latest verison on linux, I had to add this header.
> added stdint.h to compile igtlH264 on linux

- CMakeLists.txt
This commit increases the template-depth to 900 to avoid compilation issue
when building application with C++11 against Qt5.
The value of 900 was selected because it is the default with gcc.
See https://gcc.gnu.org/onlinedocs/gcc-4.8.2/gcc/C_002b_002b-Dialect-Options.html#C_002b_002b-Dialect-Options
and https://stackoverflow.com/questions/23374953/why-does-this-exceed-the-maximum-recursive-template-depth#comment35810463_23376156
> COMP: Do not constraint project depending on OpenIGTLink with template-depth of 50

- CMakeLists.txt
This will steamline infegration of OpenIGTLink by not contraining downstream
project to a specific template depth.
Adapted from InsightSoftwareConsortium/ITK@5bcca74
> COMP: Modern gcc compilers have a reasonable template depth limit

- Source/igtlNDArrayMessage.h
I noticed that the size of the type in the `Array<T>` type is taken twice into account.
Previously this code used bytewise indexing, which made necessary multiplying the input index with the size of the type:
https://github.com/openigtlink/OpenIGTLink/blob/5acf3b41a91160b3bb875fd3bb66ae87596e4ea2/Source/igtlNDArrayMessage.h#L94
However, after casting the raw array to `T*` in the `ByteArray` variable, indexing already takes into account the size of the type.
The current code would produce out-of-bounds access for types with size > 1 byte and input indices > 1.
https://github.com/openigtlink/OpenIGTLink/blob/1d6cd5ce750e3b4edba340646247d1b297ea43fa/Source/igtlNDArrayMessage.h#L95
Additionally, I changed the variable name to `TypeArray` to make it clearer and used `reinterpret_cast` instead …
> Fix indexing of type array after conversion

- Source/igtlSessionManager.cxx
when client try to connect and it's failed, then return 0.
> Add return exception 

- Source/VideoStreaming/igtlCodecCommonClasses.h
- Source/VideoStreaming/igtlVP9Decoder.cxx
- Source/VideoStreaming/igtlVP9Decoder.h
- Source/VideoStreaming/igtlVP9Encoder.cxx
- Source/VideoStreaming/igtlVP9Encoder.h
- Testing/igtlVideoMessageTest.cxx
The user will have the possibility to send RGB or YUV444 data directly. This will have great benefit as the current I420 format requires user to convert RGB data to YUV420, which will cause color lost.
> FEATURE: I444 data format added for compression using VP9

- CMakeLists.txt
- Examples/Receiver/ReceiveClient.cxx
I used the example `ReceiveClient` quite a bit for debugging purposes.  I added a function to display the content of `igtl::SensorMessage` as well as the `DeviceName`.  The device name is useful when sending multiple types on messages on the same port.
> EHN: ReceiveClient, added support for SensorMessage, display DeviceName

- Source/igtlMessageBase.cxx
- Source/igtlMessageBase.h
Reverts openigtlink/OpenIGTLink#230,
crc option flag needs to be sent via meta data and is only available for header_version 2.
> Revert "ENH: Adding parameter to Pack() to make crc calculation optional"

- Source/igtlMessageBase.cxx
- Testing/igtlStatusMessageTest.cxx
It is possible to crash receivers by sending messages with corrupted meta data information, because there is no validation of the meta data length that is send. Thus, other OpenIGTLink end points can easily be crashed by sending such messages.
Furthermore, such a failed message unpacking is not propagated along the call hierarchy resulting in further processing of corrupted/invalid messages.
- ensure that amount of bytes read from metaData does not exceed expected meta data length
- do not set m_IsBodyUnpacked and UNPACK_BODY if unpacking failed
> MetaDataValidation

- Source/igtlMessageBase.cxx
When unpacking a message with a v1 header, igtlMessageBase::UnpackHeader attempted to unpack the extended header and metadata. This resulted in failure since neither are valid for v1 headers.
Fixed by only attempting to unpack the extended header and metadata for header version >= 2.
> BUG: Fix error when unpacking messages with v1 header

- Examples/VideoStreaming/VideoClient.cxx
- Examples/VideoStreaming/VideoMetaClient.cxx
- Examples/VideoStreaming/VideoMetaServer.cxx
- Examples/VideoStreaming/VideoServer.cxx
- SuperBuild/External_openh264.cmake
Update openh264 include path
Update video streaming example to new Receive() with timeout
openh264 [commit 3164a792a8a22f9d7456c7e2db9280ce5cc7e31b](https://github.com/cisco/openh264/commit/3164a792a8a22f9d7456c7e2db9280ce5cc7e31b) has moved the `codec/api/svc` directory to `codec/api/wels` which breaks video streaming + h264 build.
Additionally, updates the video streaming examples to use new Socket::Receive() function prototype.
> FIX: Video streaming build fixes

- Source/igtlLightObject.cxx
In the destructor of the igtlLightObject, a call to
std::uncaught_exception was used. This function was deprecated in C++17
and then removed in C++20, which causes OpenIGTLink to fail compilation
on Visual Studio if C++20 is enabled.
Judging from the comments in the code, the call was unnecessary, so it
was removed.
> FIX: make code compile under C++20

- Source/igtlutil/igtl_ndarray.h
Adding a little example on the documentation for `igtl_ndarray_alloc_info()` to make it obvious for everybody how the `size` array is to be prepared.
> Extra igtl_ndarray.h documentation.

- Source/igtlLightObject.cxx
Assigning string literals to `char*` has been [illegal since C++11][1], but Visual Studio only started to enforce this in C++20 mode, where the [`/permissive` flag is disabled by default][2]. With this small change, the project now also compiles in Visual Studio's C++20 mode.
[1]: https://en.cppreference.com/w/cpp/language/string_literal
[2]: https://learn.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=msvc-160
> FIX: make sure to assign string literals to `const char*`

- Source/igtlSocket.cxx
Before closing a socket, the application should call shutdown to ensure that all data is sent and received on the closed socket. If closesocket is called without calling shutdown, any data that has not been sent may be lost.
https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-closesocket
> BUG: Call shutdown when closing socket on Windows
